
# ##########################################################
# Package

[package]

authors = [
	"Matt Wilson <matthew@synesis.com.au>",
]
categories = [
	"development-tools::build-utils",
]
description = "Build tools, for Rust"
documentation = "https://docs.rs/bt-rs"
edition = "2021"
exclude = [
	".cargo",
	".cursor",
	".github",
	".vimrc",
	".vscode",
	"scripts",
	"target",
]
homepage = "https://github.com/synesissoftware/bt-rs"
keywords = [
	"build",
	"cargo",
	"rust",
	"tools",
]
license = "BSD-3-Clause"
name = "bt-rs"
readme = "README.md"
repository = "https://github.com/synesissoftware/bt-rs"
rust-version = "1.74"
version = "0.0.3"


# ##########################################################
# Targets

[lib]
name = "bt_rs"
path = "src/lib.rs"


# ##########################################################
# Features

[features]

default = [
]

# General features:
#
# - "_NEVER_TO_BE_ENABLED" - this is a placeholder feature and must NEVER be specified;
# - "null-feature" - a feature that has no effect (and, thus, is useful for simplifying driver scripts);

_NEVER_TO_BE_ENABLED = []
null-feature = []


# Crate-specific features:
#


# ##########################################################
# Dependencies

[build-dependencies]

[dependencies]

[dev-dependencies]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
